[workspace]
members = [
    "crates/anymon-core",
    "crates/anymon-config",
    "crates/anymon-runner",
    "crates/anymon-shell",
]
resolver = "1"

[workspace.package]
authors = ["Anymon Contributors"]
version = "0.7.0"
edition = "2021"
license = "MIT OR Apache-2.0"