[package]
name = "anymon-config"
version = "0.1.0"
edition = "2021"
description = "Config parsing for anymon"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.9"
anyhow = "1"
